import type { ReactNode } from 'react';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps): React.ReactElement {
  return (
    <html lang="es">
      <body>{children}</body>
    </html>
  );
}